# "$schema" = "../target/config-schema.json"

env = "dev"
target = "limatoukka"

display = ":17"

valkey = "redis://localhost:6379"
loki = "http://localhost:3030"
otel = "http://localhost:4318/v1/traces"

browser_source_bind = "localhost:7456"
