# "$schema" = "../target/config-schema.json"

env = "prod"
target = "necauqua"

display = ":17"

valkey = "redis://localhost:6379"

browser-source-bind = "localhost:7456"

vote-min-ratio = 0.7
vote-trigger-people = 2

[kick-votes]
trigger-interval = "30s"
vote-time = "1m"

[restart-votes]
trigger-interval = "30s"
vote-time = "1m"

[reset-votes]
trigger-interval = "30s"
vote-time = "2m"
