# "$schema" = "../target/config-schema.json"

env = "prod"

valkey = "redis://localhost:6379"

browser-source-bind = "localhost:7456"
music-player-bind = "localhost:35354"

#
# Real values in gitignored config.private.toml, this might drift over time
#

# [twitch]
# client-id = "<SECRET>"
# client-secret = "<SECRET>"
# redirect-url = "http://localhost:12312"
# target-channel = "necauqua"

# [elastic]
# url = "<HOST>"
# api-key = "<SECRET>"
# index = "twitch-chat-necauqua"

# [stats]
# url = "<HOST>"
# api-key = "<SECRET>"
# index = "limatoukka-stats"

# [youtube]
# api-key = "<SECRET>"
# playlist = "<PLAYLIST-ID>"
# country-code = "UA"

# [ntfy]
# host = "<HOST>"

# [ntfy.topic.kofi]
# token = "<SECRET>"
